### ISSUE TITLE
MultiLineStringField generation does not work

### ISSUE THREAD

**Issue by fletort** [sigma-geosistemas/mommy_spatial_generators#2]
Here the error that i have when trying to generate a model with a MultiLineStringField : 

> File "/usr/django/app/src/mommy-spatial-generators/mommy_spatial_generators/generators.py", line 99, in gen_multilinestring
    return MultiPolygon([gen_linestring(min_x, min_y, max_x, max_y, srid) for i in range(gen_integer(min_linestrings, max_linestrings+1))])
  File "/usr/django/app/src/mommy-spatial-generators/mommy_spatial_generators/generators.py", line 99, in <listcomp>
    return MultiPolygon([gen_linestring(min_x, min_y, max_x, max_y, srid) for i in range(gen_integer(min_linestrings, max_linestrings+1))])
  File "/usr/django/app/src/mommy-spatial-generators/mommy_spatial_generators/generators.py", line 86, in gen_linestring
    return LineString(points)
  File "/usr/local/lib/python3.5/site-packages/django/contrib/gis/geos/linestring.py", line 42, in __init__
    raise TypeError('Cannot initialize on empty sequence.')
TypeError: Cannot initialize on empty sequence.

**Comment by george-silva** [comment]
Let me check...

**Comment by fletort** [comment]
Any news on this problem ? I success to create LineString but not MultiLineStringField.

**Comment by george-silva** [comment]
I saw a problem indeed and I'm fixing it. Also I'm fixing the tests and creating better packaging, so we can distribute this easier.

It will take a while, but I'll try to push an update today.
